export type Severity = "critical" | "high" | "medium" | "low";

export const SEVERITY_ORDER: Severity[] = ["critical", "high", "medium", "low"];

export const SEVERITY_STYLES: Record<Severity, string> = {
  critical: "border-critical/40 bg-critical/15 text-critical",
  high: "border-high/40 bg-high/15 text-high",
  medium: "border-medium/40 bg-medium/15 text-medium",
  low: "border-low/40 bg-low/15 text-low",
};

export const SEVERITY_WEIGHT: Record<Severity, number> = {
  critical: 25,
  high: 14,
  medium: 7,
  low: 2,
};

export type ComplianceRef = {
  framework: string;
  clause: string;
  requirement: string;
};

export function frameworkStyle(framework: string) {
  const f = framework.toUpperCase();
  if (f.includes("DPDP")) return "border-dpdp/40 bg-dpdp/10 text-dpdp";
  if (f.includes("RBI")) return "border-rbi/40 bg-rbi/10 text-rbi";
  return "border-border bg-secondary text-muted-foreground";
}

export function riskLabel(score: number) {
  if (score >= 75) return "Blocked";
  if (score >= 45) return "Needs review";
  if (score >= 20) return "Minor issues";
  return "Clean";
}

export const STACK_OPTIONS = [
  { value: "auto", label: "Auto-detect" },
  { value: "node-ts-aws", label: "Node.js + TypeScript + React + AWS" },
  { value: "python-django-aws", label: "Python + Django/FastAPI + React + Postgres" },
  { value: "terraform", label: "Terraform / CDK infrastructure" },
] as const;

export const SAMPLE_DIFF = `// PATCH: src/routes/api/payouts.ts  (AI-generated by Copilot)
export async function POST(req: Request) {
  const body = await req.json();

  // fetch customer KYC record
  const { rows } = await db.query(
    \`SELECT * FROM customers WHERE pan = '\${body.pan}'\`
  );

  console.log("payout request", body.pan, body.aadhaar, rows[0]);

  await s3.putObject({
    Bucket: "kyc-docs-prod",
    Key: \`\${body.pan}.json\`,
    Body: JSON.stringify(rows[0]),
    ACL: "public-read",
  });

  const token = jwt.sign({ uid: rows[0].id }, "dev-secret-123");
  return Response.json({ ok: true, token, customer: rows[0] });
}`;
